In [13]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_csv(r"D:\USER\Downloads\QualityCapture-30-120\Line_Stop_History_Report_original.csv")
df

,Date,Station_Name,Serial_No,Primary_Owner,Secondary_Owner,Stop_Time,Resume_Time,Duration,ActualLineLoss,Line_Stop_By,Stop_Reason,Remarks
0,01 Apr 2022,VTU-110,NMBKK6697,NaN,NaN,01/04/2022 17:12:56,01/04/2022 18:10:24,00:53:24,00:53:24,"23255071, 23260759",Line stopped due to Emergency Call,Line stopped due to Emergency Call
1,01 Apr 2022,VTU-110,NaN,NaN,NaN,01/04/2022 18:10:24,01/04/2022 18:11:11,00:00:47,00:00:47,NaN,Conveyor Not Connected,Line stopped due to Conveyor Not Connected
2,01 Apr 2022,VTU-110,NMBKK6697,NaN,NaN,01/04/2022 18:11:11,01/04/2022 18:29:36,00:18:25,00:18:25,"23255071, 23260759",Line stopped due to Emergency Call,Line stopped due to Emergency Call
3,01 Apr 2022,VTU-80,NMBKK6700,NaN,NaN,01/04/2022 18:30:57,01/04/2022 18:30:56,00:00:01,00:00:01,5869007868,Quality data not saved,Main part SerialNo. not scanned on the station
4,01 Apr 2022,VTU-100,NMBKK6698,NaN,NaN,01/04/2022 18:30:57,01/04/2022 18:36:17,00:05:20,00:05:20,"23260759, 23261474",Quality data not saved,Main part SerialNo. not scanned on the station
...,...,...,...,...,...,...,...,...,...,...,...,...
87700,30 Sep 2022,VTU-110,NFAAB8447,NaN,NaN,30/09/2022 23:51:58,30/09/2022 23:52:15,00:00:17,NaN,"23255053, 23255086",Line stopped due to Emergency Call,Line stopped due to Emergency Call
87701,30 Sep 2022,VTU-30,NFAAB8457,NaN,NaN,30/09/2022 23:54:03,30/09/2022 23:54:43,00:00:40,NaN,23255061,Quality data not saved,Main part SerialNo. not scanned on the station
87702,30 Sep 2022,VTU-110,NFAAB8449,NaN,NaN,30/09/2022 23:54:46,30/09/2022 23:55:03,00:00:17,NaN,"23255053, 23255086",Line stopped due to Emergency Call,Line stopped due to Emergency Call
87703,30 Sep 2022,VTU-40,NFAAB8457,NaN,NaN,30/09/2022 23:56:59,01/10/2022 06:54:00,00:09:00,NaN,23276445,Quality data not saved,Main part SerialNo. not scanned on the station
87704,30 Sep 2022,VTU-30,NFAAB8458,NaN,NaN,30/09/2022 23:56:59,30/09/2022 23:57:47,00:00:48,NaN,23255061,Quality data not saved,Main part SerialNo. not scanned on the station

In [15]:
stations_dict = {
'VTU-30':'VTU-030',
'VTU-40':'VTU-040',
'VTU-60' :'VTU-060',
'VTU-70' :'VTU-070',
'VTU-80' :'VTU-080',
'VTU-90':'VTU-090',
}
stations_list = [
 'VTU-030',
 'VTU-040',
 'VTU-060',
 'VTU-070',
 'VTU-080',
 'VTU-090',
 'VTU-100',
 'VTU-110',
 'VTU-120',
 ]

In [16]:
#replace Station_Names using stations_dict
df['Station_Name'] = df['Station_Name'].replace(stations_dict)
df

,Date,Station_Name,Serial_No,Primary_Owner,Secondary_Owner,Stop_Time,Resume_Time,Duration,ActualLineLoss,Line_Stop_By,Stop_Reason,Remarks
0,01 Apr 2022,VTU-110,NMBKK6697,NaN,NaN,01/04/2022 17:12:56,01/04/2022 18:10:24,00:53:24,00:53:24,"23255071, 23260759",Line stopped due to Emergency Call,Line stopped due to Emergency Call
1,01 Apr 2022,VTU-110,NaN,NaN,NaN,01/04/2022 18:10:24,01/04/2022 18:11:11,00:00:47,00:00:47,NaN,Conveyor Not Connected,Line stopped due to Conveyor Not Connected
2,01 Apr 2022,VTU-110,NMBKK6697,NaN,NaN,01/04/2022 18:11:11,01/04/2022 18:29:36,00:18:25,00:18:25,"23255071, 23260759",Line stopped due to Emergency Call,Line stopped due to Emergency Call
3,01 Apr 2022,VTU-080,NMBKK6700,NaN,NaN,01/04/2022 18:30:57,01/04/2022 18:30:56,00:00:01,00:00:01,5869007868,Quality data not saved,Main part SerialNo. not scanned on the station
4,01 Apr 2022,VTU-100,NMBKK6698,NaN,NaN,01/04/2022 18:30:57,01/04/2022 18:36:17,00:05:20,00:05:20,"23260759, 23261474",Quality data not saved,Main part SerialNo. not scanned on the station
...,...,...,...,...,...,...,...,...,...,...,...,...
87700,30 Sep 2022,VTU-110,NFAAB8447,NaN,NaN,30/09/2022 23:51:58,30/09/2022 23:52:15,00:00:17,NaN,"23255053, 23255086",Line stopped due to Emergency Call,Line stopped due to Emergency Call
87701,30 Sep 2022,VTU-030,NFAAB8457,NaN,NaN,30/09/2022 23:54:03,30/09/2022 23:54:43,00:00:40,NaN,23255061,Quality data not saved,Main part SerialNo. not scanned on the station
87702,30 Sep 2022,VTU-110,NFAAB8449,NaN,NaN,30/09/2022 23:54:46,30/09/2022 23:55:03,00:00:17,NaN,"23255053, 23255086",Line stopped due to Emergency Call,Line stopped due to Emergency Call
87703,30 Sep 2022,VTU-040,NFAAB8457,NaN,NaN,30/09/2022 23:56:59,01/10/2022 06:54:00,00:09:00,NaN,23276445,Quality data not saved,Main part SerialNo. not scanned on the station
87704,30 Sep 2022,VTU-030,NFAAB8458,NaN,NaN,30/09/2022 23:56:59,30/09/2022 23:57:47,00:00:48,NaN,23255061,Quality data not saved,Main part SerialNo. not scanned on the station

In [17]:
#remove null value from df
df = df[df['Stop_Reason'].notna()]

In [18]:
#check number of null values for each column
df.isnull().sum()

Date                   0
Station_Name           0
Serial_No           2178
Primary_Owner      87705
Secondary_Owner    87705
Stop_Time              0
Resume_Time            0
Duration               0
ActualLineLoss       614
Line_Stop_By       23181
Stop_Reason            0
Remarks                0
dtype: int64

In [19]:
df.drop(columns=['Primary_Owner','Secondary_Owner','Line_Stop_By'], inplace=True)

In [20]:
df.isnull().sum()

Date                 0
Station_Name         0
Serial_No         2178
Stop_Time            0
Resume_Time          0
Duration             0
ActualLineLoss     614
Stop_Reason          0
Remarks              0
dtype: int64

In [21]:
#remove null values from df['Serial_No']
df = df[df['Serial_No'].notna()]

In [22]:
df = df[df['ActualLineLoss'].notna()]

In [23]:
len(df)

84924

In [24]:
#select rows where Date in ['29 Sep 2022','30 Sep 2022']
# df = df[df['Date'].isin(['29 Sep 2022','30 Sep 2022'])]
# len(df)

In [25]:
df = df[df['Date'].isin(['27 Sep 2022','28 Sep 2022'])]
len(df)

1635

In [26]:
#convert ActualLineLoss to seconds
# df['ActualLineLoss'] = pd.to_timedelta(df['ActualLineLoss'])
df['ActualLineLoss_secs'] = (pd.to_timedelta(df['ActualLineLoss'])).dt.total_seconds()
df

,Date,Station_Name,Serial_No,Stop_Time,Resume_Time,Duration,ActualLineLoss,Stop_Reason,Remarks,ActualLineLoss_secs
84421,27 Sep 2022,VTU-110,NFBHB7136,27/09/2022 06:52:33,27/09/2022 06:52:47,00:00:14,00:00:14,Line stopped due to Emergency Call,Line stopped due to Emergency Call,14.0
84422,27 Sep 2022,VTU-110,NFBHB7137,27/09/2022 06:52:57,27/09/2022 06:54:20,00:01:23,00:01:23,Line stopped due to Emergency Call,Line stopped due to Emergency Call,83.0
84424,27 Sep 2022,VTU-040,NFANA7144,27/09/2022 06:56:04,27/09/2022 06:57:01,00:00:57,00:00:00,Quality data not saved,Main part SerialNo. not scanned on the station,0.0
84425,27 Sep 2022,VTU-080,NFANA7140,27/09/2022 06:56:04,27/09/2022 06:57:09,00:01:05,00:00:54,Quality data not saved,Main part SerialNo. not scanned on the station,54.0
84426,27 Sep 2022,VTU-090,NFANA7139,27/09/2022 06:56:04,27/09/2022 06:58:37,00:02:33,00:01:28,Quality data not saved,Main part SerialNo. not scanned on the station,88.0
...,...,...,...,...,...,...,...,...,...,...
86101,28 Sep 2022,VTU-110,NFCKN7781,28/09/2022 23:38:03,28/09/2022 23:38:13,00:00:10,00:00:00,Line stopped due to Emergency Call,Line stopped due to Emergency Call,0.0
86102,28 Sep 2022,VTU-080,NFCKN7784,28/09/2022 23:40:12,28/09/2022 23:40:33,00:00:21,00:00:21,PokaYoke,Interlock CV M8 Bolt,21.0
86103,28 Sep 2022,VTU-080,NFCKN7784,28/09/2022 23:40:12,28/09/2022 23:40:27,00:00:15,00:00:00,PokaYoke,VTU to CV joint stage,0.0
86104,28 Sep 2022,VTU-110,NFCKN7782,28/09/2022 23:40:28,28/09/2022 23:40:29,00:00:01,00:00:00,Line stopped due to Emergency Call,Line stopped due to Emergency Call,0.0
86106,28 Sep 2022,VTU-110,NFCKN7782,28/09/2022 23:42:32,28/09/2022 23:42:45,00:00:13,00:00:13,Line stopped due to Emergency Call,Line stopped due to Emergency Call,13.0

In [27]:
df['ActualLineLoss_secs'].isnull().sum()

0

In [28]:
df[df['ActualLineLoss_secs'] != 0]

,Date,Station_Name,Serial_No,Stop_Time,Resume_Time,Duration,ActualLineLoss,Stop_Reason,Remarks,ActualLineLoss_secs
84421,27 Sep 2022,VTU-110,NFBHB7136,27/09/2022 06:52:33,27/09/2022 06:52:47,00:00:14,00:00:14,Line stopped due to Emergency Call,Line stopped due to Emergency Call,14.0
84422,27 Sep 2022,VTU-110,NFBHB7137,27/09/2022 06:52:57,27/09/2022 06:54:20,00:01:23,00:01:23,Line stopped due to Emergency Call,Line stopped due to Emergency Call,83.0
84425,27 Sep 2022,VTU-080,NFANA7140,27/09/2022 06:56:04,27/09/2022 06:57:09,00:01:05,00:00:54,Quality data not saved,Main part SerialNo. not scanned on the station,54.0
84426,27 Sep 2022,VTU-090,NFANA7139,27/09/2022 06:56:04,27/09/2022 06:58:37,00:02:33,00:01:28,Quality data not saved,Main part SerialNo. not scanned on the station,88.0
84428,27 Sep 2022,VTU-060,NFANA7141,27/09/2022 06:56:05,27/09/2022 06:59:33,00:03:28,00:00:56,Quality data not saved,Main part SerialNo. not scanned on the station,56.0
...,...,...,...,...,...,...,...,...,...,...
86096,28 Sep 2022,VTU-090,NFCKN7782,28/09/2022 23:35:30,28/09/2022 23:35:51,00:00:21,00:00:21,PokaYoke,CV Mtg M10 bolt by DC tool,21.0
86098,28 Sep 2022,VTU-080,NFCKN7784,28/09/2022 23:37:52,28/09/2022 23:38:12,00:00:20,00:00:20,PokaYoke,VTU to CV joint stage,20.0
86100,28 Sep 2022,VTU-090,NFCKN7783,28/09/2022 23:37:52,28/09/2022 23:38:19,00:00:27,00:00:07,PokaYoke,CV Mtg M10 bolt by DC tool,7.0
86102,28 Sep 2022,VTU-080,NFCKN7784,28/09/2022 23:40:12,28/09/2022 23:40:33,00:00:21,00:00:21,PokaYoke,Interlock CV M8 Bolt,21.0
86106,28 Sep 2022,VTU-110,NFCKN7782,28/09/2022 23:42:32,28/09/2022 23:42:45,00:00:13,00:00:13,Line stopped due to Emergency Call,Line stopped due to Emergency Call,13.0

In [29]:
#create column Duration_secs from Duration
# df['Duration_secs'] = (pd.to_timedelta(df['Duration'])).dt.total_seconds()
# df[df['Duration_secs'] != df['ActualLineLoss_secs'] == 0]

In [30]:
# df['MCSPS'] = 0
df = df[df['ActualLineLoss_secs'] != 0]
df

,Date,Station_Name,Serial_No,Stop_Time,Resume_Time,Duration,ActualLineLoss,Stop_Reason,Remarks,ActualLineLoss_secs
84421,27 Sep 2022,VTU-110,NFBHB7136,27/09/2022 06:52:33,27/09/2022 06:52:47,00:00:14,00:00:14,Line stopped due to Emergency Call,Line stopped due to Emergency Call,14.0
84422,27 Sep 2022,VTU-110,NFBHB7137,27/09/2022 06:52:57,27/09/2022 06:54:20,00:01:23,00:01:23,Line stopped due to Emergency Call,Line stopped due to Emergency Call,83.0
84425,27 Sep 2022,VTU-080,NFANA7140,27/09/2022 06:56:04,27/09/2022 06:57:09,00:01:05,00:00:54,Quality data not saved,Main part SerialNo. not scanned on the station,54.0
84426,27 Sep 2022,VTU-090,NFANA7139,27/09/2022 06:56:04,27/09/2022 06:58:37,00:02:33,00:01:28,Quality data not saved,Main part SerialNo. not scanned on the station,88.0
84428,27 Sep 2022,VTU-060,NFANA7141,27/09/2022 06:56:05,27/09/2022 06:59:33,00:03:28,00:00:56,Quality data not saved,Main part SerialNo. not scanned on the station,56.0
...,...,...,...,...,...,...,...,...,...,...
86096,28 Sep 2022,VTU-090,NFCKN7782,28/09/2022 23:35:30,28/09/2022 23:35:51,00:00:21,00:00:21,PokaYoke,CV Mtg M10 bolt by DC tool,21.0
86098,28 Sep 2022,VTU-080,NFCKN7784,28/09/2022 23:37:52,28/09/2022 23:38:12,00:00:20,00:00:20,PokaYoke,VTU to CV joint stage,20.0
86100,28 Sep 2022,VTU-090,NFCKN7783,28/09/2022 23:37:52,28/09/2022 23:38:19,00:00:27,00:00:07,PokaYoke,CV Mtg M10 bolt by DC tool,7.0
86102,28 Sep 2022,VTU-080,NFCKN7784,28/09/2022 23:40:12,28/09/2022 23:40:33,00:00:21,00:00:21,PokaYoke,Interlock CV M8 Bolt,21.0
86106,28 Sep 2022,VTU-110,NFCKN7782,28/09/2022 23:42:32,28/09/2022 23:42:45,00:00:13,00:00:13,Line stopped due to Emergency Call,Line stopped due to Emergency Call,13.0

In [31]:
#create column index values as index
df = df.reset_index(drop=True)
df['index'] = df.index
df

,Date,Station_Name,Serial_No,Stop_Time,Resume_Time,Duration,ActualLineLoss,Stop_Reason,Remarks,ActualLineLoss_secs,index
0,27 Sep 2022,VTU-110,NFBHB7136,27/09/2022 06:52:33,27/09/2022 06:52:47,00:00:14,00:00:14,Line stopped due to Emergency Call,Line stopped due to Emergency Call,14.0,0
1,27 Sep 2022,VTU-110,NFBHB7137,27/09/2022 06:52:57,27/09/2022 06:54:20,00:01:23,00:01:23,Line stopped due to Emergency Call,Line stopped due to Emergency Call,83.0,1
2,27 Sep 2022,VTU-080,NFANA7140,27/09/2022 06:56:04,27/09/2022 06:57:09,00:01:05,00:00:54,Quality data not saved,Main part SerialNo. not scanned on the station,54.0,2
3,27 Sep 2022,VTU-090,NFANA7139,27/09/2022 06:56:04,27/09/2022 06:58:37,00:02:33,00:01:28,Quality data not saved,Main part SerialNo. not scanned on the station,88.0,3
4,27 Sep 2022,VTU-060,NFANA7141,27/09/2022 06:56:05,27/09/2022 06:59:33,00:03:28,00:00:56,Quality data not saved,Main part SerialNo. not scanned on the station,56.0,4
...,...,...,...,...,...,...,...,...,...,...,...
988,28 Sep 2022,VTU-090,NFCKN7782,28/09/2022 23:35:30,28/09/2022 23:35:51,00:00:21,00:00:21,PokaYoke,CV Mtg M10 bolt by DC tool,21.0,988
989,28 Sep 2022,VTU-080,NFCKN7784,28/09/2022 23:37:52,28/09/2022 23:38:12,00:00:20,00:00:20,PokaYoke,VTU to CV joint stage,20.0,989
990,28 Sep 2022,VTU-090,NFCKN7783,28/09/2022 23:37:52,28/09/2022 23:38:19,00:00:27,00:00:07,PokaYoke,CV Mtg M10 bolt by DC tool,7.0,990
991,28 Sep 2022,VTU-080,NFCKN7784,28/09/2022 23:40:12,28/09/2022 23:40:33,00:00:21,00:00:21,PokaYoke,Interlock CV M8 Bolt,21.0,991
992,28 Sep 2022,VTU-110,NFCKN7782,28/09/2022 23:42:32,28/09/2022 23:42:45,00:00:13,00:00:13,Line stopped due to Emergency Call,Line stopped due to Emergency Call,13.0,992

In [32]:
df = df[df['Station_Name']!= 'VTU-Masking']

In [33]:
df = df[df['Station_Name'] != 'VTU-50']

In [34]:
df['Time'] = pd.to_datetime(df['Stop_Time'])

In [35]:
#group by Station_Name
df_group = df.groupby('Station_Name')
#create df for each group
df_group_list = [df_group.get_group(x) for x in df_group.groups]
new_df = pd.DataFrame()
for name, group in df_group:
    ef = df_group.get_group(name) 
    ef['Stop_Time']  = pd.to_datetime(ef['Stop_Time'])
    ef['Stop_1'] = ef['Stop_Time'].shift(1)
    ef['Timesince_Previous_Stop'] = (ef['Stop_Time'] - ef['Stop_1']).dt.total_seconds()//60
    ef.dropna(inplace=True)
    ef['Timesince_Previous_Stop'] = ef['Timesince_Previous_Stop'].astype(int)
    new_df = pd.concat([new_df, ef], ignore_index=True)

<ipython-input-35-e7beb2c29ba4>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Stop_Time']  = pd.to_datetime(ef['Stop_Time'])
<ipython-input-35-e7beb2c29ba4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Stop_1'] = ef['Stop_Time'].shift(1)
<ipython-input-35-e7beb2c29ba4>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Timesince_Previous_Stop'] = (ef['Stop_Time'] - ef['Stop_1']).dt.total_seconds()//60
<ipython-input-35-e7beb2c29ba4>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef.dropna(inplace=True)
<ipython-input-35-e7beb2c29ba4>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Timesince_Previous_Stop'] = ef['Timesince_Previous_Stop'].astype(int)
<ipython-input-35-e7beb2c29ba4>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Stop_Time']  = pd.to_datetime(ef['Stop_Time'])
<ipython-input-35-e7beb2c29ba4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Stop_1'] = ef['Stop_Time'].shift(1)
<ipython-input-35-e7beb2c29ba4>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Timesince_Previous_Stop'] = (ef['Stop_Time'] - ef['Stop_1']).dt.total_seconds()//60
<ipython-input-35-e7beb2c29ba4>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef.dropna(inplace=True)
<ipython-input-35-e7beb2c29ba4>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Timesince_Previous_Stop'] = ef['Timesince_Previous_Stop'].astype(int)
<ipython-input-35-e7beb2c29ba4>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Stop_Time']  = pd.to_datetime(ef['Stop_Time'])
<ipython-input-35-e7beb2c29ba4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Stop_1'] = ef['Stop_Time'].shift(1)
<ipython-input-35-e7beb2c29ba4>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Timesince_Previous_Stop'] = (ef['Stop_Time'] - ef['Stop_1']).dt.total_seconds()//60
<ipython-input-35-e7beb2c29ba4>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef.dropna(inplace=True)
<ipython-input-35-e7beb2c29ba4>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Timesince_Previous_Stop'] = ef['Timesince_Previous_Stop'].astype(int)
<ipython-input-35-e7beb2c29ba4>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Stop_Time']  = pd.to_datetime(ef['Stop_Time'])
<ipython-input-35-e7beb2c29ba4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Stop_1'] = ef['Stop_Time'].shift(1)
<ipython-input-35-e7beb2c29ba4>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Timesince_Previous_Stop'] = (ef['Stop_Time'] - ef['Stop_1']).dt.total_seconds()//60
<ipython-input-35-e7beb2c29ba4>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef.dropna(inplace=True)
<ipython-input-35-e7beb2c29ba4>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Timesince_Previous_Stop'] = ef['Timesince_Previous_Stop'].astype(int)
<ipython-input-35-e7beb2c29ba4>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Stop_Time']  = pd.to_datetime(ef['Stop_Time'])
<ipython-input-35-e7beb2c29ba4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Stop_1'] = ef['Stop_Time'].shift(1)
<ipython-input-35-e7beb2c29ba4>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Timesince_Previous_Stop'] = (ef['Stop_Time'] - ef['Stop_1']).dt.total_seconds()//60
<ipython-input-35-e7beb2c29ba4>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef.dropna(inplace=True)
<ipython-input-35-e7beb2c29ba4>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Timesince_Previous_Stop'] = ef['Timesince_Previous_Stop'].astype(int)
<ipython-input-35-e7beb2c29ba4>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Stop_Time']  = pd.to_datetime(ef['Stop_Time'])
<ipython-input-35-e7beb2c29ba4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Stop_1'] = ef['Stop_Time'].shift(1)
<ipython-input-35-e7beb2c29ba4>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Timesince_Previous_Stop'] = (ef['Stop_Time'] - ef['Stop_1']).dt.total_seconds()//60
<ipython-input-35-e7beb2c29ba4>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef.dropna(inplace=True)
<ipython-input-35-e7beb2c29ba4>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Timesince_Previous_Stop'] = ef['Timesince_Previous_Stop'].astype(int)
<ipython-input-35-e7beb2c29ba4>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Stop_Time']  = pd.to_datetime(ef['Stop_Time'])
<ipython-input-35-e7beb2c29ba4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Stop_1'] = ef['Stop_Time'].shift(1)
<ipython-input-35-e7beb2c29ba4>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Timesince_Previous_Stop'] = (ef['Stop_Time'] - ef['Stop_1']).dt.total_seconds()//60
<ipython-input-35-e7beb2c29ba4>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef.dropna(inplace=True)
<ipython-input-35-e7beb2c29ba4>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Timesince_Previous_Stop'] = ef['Timesince_Previous_Stop'].astype(int)
<ipython-input-35-e7beb2c29ba4>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Stop_Time']  = pd.to_datetime(ef['Stop_Time'])
<ipython-input-35-e7beb2c29ba4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Stop_1'] = ef['Stop_Time'].shift(1)
<ipython-input-35-e7beb2c29ba4>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Timesince_Previous_Stop'] = (ef['Stop_Time'] - ef['Stop_1']).dt.total_seconds()//60
<ipython-input-35-e7beb2c29ba4>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef.dropna(inplace=True)
<ipython-input-35-e7beb2c29ba4>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ef['Timesince_Previous_Stop'] = ef['Timesince_Previous_Stop'].astype(int)

In [36]:
# new_df['Timesince_Previous_Stop'] = (new_df['Stop_Time'] - new_df['Stop_1']).dt.total_seconds()//60
# new_df['Timesince_Previous_Stop'] = new_df['Timesince_Previous_Stop'].astype(int)

In [37]:
new_df

,Date,Station_Name,Serial_No,Stop_Time,Resume_Time,Duration,ActualLineLoss,Stop_Reason,Remarks,ActualLineLoss_secs,index,Time,Stop_1,Timesince_Previous_Stop
0,27 Sep 2022,VTU-030,NFBKE7192,2022-09-27 09:35:27,27/09/2022 09:35:36,00:00:09,00:00:09,Quality data not saved,Main part SerialNo. not scanned on the station,9.0,43,2022-09-27 09:35:27,2022-09-27 08:21:28,73
1,27 Sep 2022,VTU-030,NFBKE7222,2022-09-27 11:35:44,27/09/2022 11:36:24,00:00:40,00:00:40,Quality data not saved,Main part SerialNo. not scanned on the station,40.0,79,2022-09-27 11:35:44,2022-09-27 09:35:27,120
2,27 Sep 2022,VTU-030,NFDKR7238,2022-09-27 12:05:54,27/09/2022 12:06:10,00:00:16,00:00:16,Quality data not saved,Main part SerialNo. not scanned on the station,16.0,93,2022-09-27 12:05:54,2022-09-27 11:35:44,30
3,27 Sep 2022,VTU-030,NFAYB7235,2022-09-27 12:25:47,27/09/2022 12:25:55,00:00:08,00:00:08,Quality data not saved,Main part SerialNo. not scanned on the station,8.0,107,2022-09-27 12:25:47,2022-09-27 12:05:54,19
4,27 Sep 2022,VTU-030,NFAYB7251,2022-09-27 13:10:47,27/09/2022 13:11:03,00:00:16,00:00:16,Quality data not saved,Main part SerialNo. not scanned on the station,16.0,128,2022-09-27 13:10:47,2022-09-27 12:25:47,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
980,28 Sep 2022,VTU-110,NFANA7771,2022-09-28 23:14:54,28/09/2022 23:15:11,00:00:17,00:00:17,Line stopped due to Emergency Call,Line stopped due to Emergency Call,17.0,973,2022-09-28 23:14:54,2022-09-28 21:48:24,86
981,28 Sep 2022,VTU-110,NFANA7775,2022-09-28 23:25:20,28/09/2022 23:25:22,00:00:02,00:00:02,Line stopped due to Emergency Call,Line stopped due to Emergency Call,2.0,980,2022-09-28 23:25:20,2022-09-28 23:14:54,10
982,28 Sep 2022,VTU-110,NFCKN7777,2022-09-28 23:30:08,28/09/2022 23:30:25,00:00:17,00:00:11,Line stopped due to Emergency Call,Line stopped due to Emergency Call,11.0,984,2022-09-28 23:30:08,2022-09-28 23:25:20,4
983,28 Sep 2022,VTU-110,NFCKN7777,2022-09-28 23:32:33,28/09/2022 23:32:50,00:00:17,00:00:17,Line stopped due to Emergency Call,Line stopped due to Emergency Call,17.0,986,2022-09-28 23:32:33,2022-09-28 23:30:08,2
984,28 Sep 2022,VTU-110,NFCKN7782,2022-09-28 23:42:32,28/09/2022 23:42:45,00:00:13,00:00:13,Line stopped due to Emergency Call,Line stopped due to Emergency Call,13.0,992,2022-09-28 23:42:32,2022-09-28 23:32:33,9

In [38]:
#sort dataframe by Stop_Time
new_df = new_df.sort_values(by=['Stop_Time'])
new_df

,Date,Station_Name,Serial_No,Stop_Time,Resume_Time,Duration,ActualLineLoss,Stop_Reason,Remarks,ActualLineLoss_secs,index,Time,Stop_1,Timesince_Previous_Stop
596,27 Sep 2022,VTU-110,NFBHB7137,2022-09-27 06:52:57,27/09/2022 06:54:20,00:01:23,00:01:23,Line stopped due to Emergency Call,Line stopped due to Emergency Call,83.0,1,2022-09-27 06:52:57,2022-09-27 06:52:33,0
597,27 Sep 2022,VTU-110,NFBHB7137,2022-09-27 06:59:38,27/09/2022 06:59:54,00:00:16,00:00:16,Line stopped due to Emergency Call,Line stopped due to Emergency Call,16.0,5,2022-09-27 06:59:38,2022-09-27 06:52:57,6
158,27 Sep 2022,VTU-060,NFANA7141,2022-09-27 06:59:57,27/09/2022 07:00:57,00:01:00,00:01:00,PokaYoke,M12 plug Interlock With Conveyor,60.0,6,2022-09-27 06:59:57,2022-09-27 06:56:05,3
598,27 Sep 2022,VTU-110,NFANA7138,2022-09-27 07:00:13,27/09/2022 07:01:47,00:01:34,00:00:50,Line stopped due to Emergency Call,Line stopped due to Emergency Call,50.0,7,2022-09-27 07:00:13,2022-09-27 06:59:38,0
599,27 Sep 2022,VTU-110,NFANA7138,2022-09-27 07:04:10,27/09/2022 07:04:26,00:00:16,00:00:16,Line stopped due to Emergency Call,Line stopped due to Emergency Call,16.0,9,2022-09-27 07:04:10,2022-09-27 07:00:13,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,28 Sep 2022,VTU-090,NFCKN7782,2022-09-28 23:35:30,28/09/2022 23:35:51,00:00:21,00:00:21,PokaYoke,CV Mtg M10 bolt by DC tool,21.0,988,2022-09-28 23:35:30,2022-09-28 23:29:40,5
426,28 Sep 2022,VTU-080,NFCKN7784,2022-09-28 23:37:52,28/09/2022 23:38:12,00:00:20,00:00:20,PokaYoke,VTU to CV joint stage,20.0,989,2022-09-28 23:37:52,2022-09-28 23:22:50,15
526,28 Sep 2022,VTU-090,NFCKN7783,2022-09-28 23:37:52,28/09/2022 23:38:19,00:00:27,00:00:07,PokaYoke,CV Mtg M10 bolt by DC tool,7.0,990,2022-09-28 23:37:52,2022-09-28 23:35:30,2
427,28 Sep 2022,VTU-080,NFCKN7784,2022-09-28 23:40:12,28/09/2022 23:40:33,00:00:21,00:00:21,PokaYoke,Interlock CV M8 Bolt,21.0,991,2022-09-28 23:40:12,2022-09-28 23:37:52,2
984,28 Sep 2022,VTU-110,NFCKN7782,2022-09-28 23:42:32,28/09/2022 23:42:45,00:00:13,00:00:13,Line stopped due to Emergency Call,Line stopped due to Emergency Call,13.0,992,2022-09-28 23:42:32,2022-09-28 23:32:33,9

In [39]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 985 entries, 596 to 984
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     985 non-null    object
 1   Station_Name             985 non-null    object
 2   Serial_No                985 non-null    object
 3   Stop_Time                985 non-null    datetime64[ns]
 4   Resume_Time              985 non-null    object
 5   Duration                 985 non-null    object
 6   ActualLineLoss           985 non-null    object
 7   Stop_Reason              985 non-null    object
 8   Remarks                  985 non-null    object
 9   ActualLineLoss_secs      985 non-null    float64
 10  index                    985 non-null    int64
 11  Time                     985 non-null    datetime64[ns]
 12  Stop_1                   985 non-null    datetime64[ns]
 13  Timesince_Previous_Stop  985 non-null    int32
dtypes: datetime64[ns](3), float64(1), int32(1), int64(1), object(8)
memory usage: 111.6+ KB

In [40]:

new_df.dropna(inplace=True)
new_df.isna().sum()

Date                       0
Station_Name               0
Serial_No                  0
Stop_Time                  0
Resume_Time                0
Duration                   0
ActualLineLoss             0
Stop_Reason                0
Remarks                    0
ActualLineLoss_secs        0
index                      0
Time                       0
Stop_1                     0
Timesince_Previous_Stop    0
dtype: int64

In [41]:
new_df = new_df.reset_index(drop=True)

In [42]:
new_df = new_df[new_df['Timesince_Previous_Stop']>0]

In [43]:
morning_time = pd.to_datetime('06:00:00').time()
morning_shift_time = pd.to_datetime('6:00:00').time()
evening_shift_time = pd.to_datetime('15:30:00').time()

In [44]:
# def select_time(Stop_Time , m, e):
#     print(type(Stop_Time),type(m),type(e))
#     if Stop_Time >= m and Stop_Time <= e:
#         return Stop_Time - pd.to_datetime(Stop_Time.year, Stop_Time.month, Stop_Time.day, 6, 0, 0)
#     else:
#         return Stop_Time - pd.to_datetime(Stop_Time.year, Stop_Time.month, Stop_Time.day, 15, 30, 0)    
def select(Time_Since_Morning_Shift, Time_Since_Evening_Shift):
    if Time_Since_Morning_Shift < 0:
        return abs(Time_Since_Evening_Shift)
    elif Time_Since_Evening_Shift < 0:
        return Time_Since_Morning_Shift
    else:
        return min(Time_Since_Morning_Shift, Time_Since_Evening_Shift)

In [45]:
#create Columnd Date1 from Stop_Time
new_df['Date1'] = pd.to_datetime(new_df['Stop_Time']).dt.date
#create Column Morning_Time using Date1 and time 07:00:00
new_df['Morning_Time'] = pd.to_datetime(new_df['Date1'].astype(str) + ' ' + morning_time.strftime('%H:%M:%S'))
#create Column Morning_Shift_Time using Date1 and time 07:00:00
new_df['Morning_Shift_Time'] = pd.to_datetime(new_df['Date1'].astype(str) + ' ' + morning_shift_time.strftime('%H:%M:%S'))
#create Column Evening_Shift_Time using Date1 and time 15:30:00
new_df['Evening_Shift_Time'] = pd.to_datetime(new_df['Date1'].astype(str) + ' ' + evening_shift_time.strftime('%H:%M:%S'))
#create Column Time_Since_Morning using Stop_Time and Morning_Time in hours
new_df['Time_Since_Morning'] = (new_df['Stop_Time'] - new_df['Morning_Time']).dt.total_seconds()//3600
#create columne Time_Since_Shift_Start using select_time function 
# new_df.info()
# new_df['Time_Since_Shift_Start'] = new_df.apply(lambda x: select_time(x['Stop_Time'], x['Morning_Shift_Time'], x['Evening_Shift_Time']), axis=1)
# #create Column Time_Since_Morning_Shift using Stop_Time and Morning_Shift_Time in hours
new_df['Time_Since_Morning_Shift'] = (new_df['Stop_Time'] - new_df['Morning_Shift_Time']).dt.total_seconds()//3600
# #create Column Time_Since_Evening_Shift using Stop_Time and Evening_Shift_Time in hours
new_df['Time_Since_Evening_Shift'] = (new_df['Stop_Time'] - new_df['Evening_Shift_Time']).dt.total_seconds()//3600
new_df['Time_Since_Shift_Start'] = new_df.apply(lambda x: select(x['Time_Since_Morning_Shift'], x['Time_Since_Evening_Shift']), axis=1)
new_df.drop(columns=['Morning_Time', 'Morning_Shift_Time', 'Evening_Shift_Time', 'Time_Since_Morning_Shift', 'Time_Since_Evening_Shift','Date1'], inplace=True)
new_df

,Date,Station_Name,Serial_No,Stop_Time,Resume_Time,Duration,ActualLineLoss,Stop_Reason,Remarks,ActualLineLoss_secs,index,Time,Stop_1,Timesince_Previous_Stop,Time_Since_Morning,Time_Since_Shift_Start
1,27 Sep 2022,VTU-110,NFBHB7137,2022-09-27 06:59:38,27/09/2022 06:59:54,00:00:16,00:00:16,Line stopped due to Emergency Call,Line stopped due to Emergency Call,16.0,5,2022-09-27 06:59:38,2022-09-27 06:52:57,6,0.0,0.0
2,27 Sep 2022,VTU-060,NFANA7141,2022-09-27 06:59:57,27/09/2022 07:00:57,00:01:00,00:01:00,PokaYoke,M12 plug Interlock With Conveyor,60.0,6,2022-09-27 06:59:57,2022-09-27 06:56:05,3,0.0,0.0
4,27 Sep 2022,VTU-110,NFANA7138,2022-09-27 07:04:10,27/09/2022 07:04:26,00:00:16,00:00:16,Line stopped due to Emergency Call,Line stopped due to Emergency Call,16.0,9,2022-09-27 07:04:10,2022-09-27 07:00:13,3,1.0,1.0
5,27 Sep 2022,VTU-080,NFANA7141,2022-09-27 07:06:29,27/09/2022 07:07:10,00:00:41,00:00:24,Quality data not saved,Main part SerialNo. not scanned on the station,24.0,10,2022-09-27 07:06:29,2022-09-27 06:56:04,10,1.0,1.0
6,27 Sep 2022,VTU-090,NFDKR7143,2022-09-27 07:06:29,27/09/2022 07:06:46,00:00:17,00:00:17,Quality data not saved,Main part SerialNo. not scanned on the station,17.0,11,2022-09-27 07:06:29,2022-09-27 06:56:04,10,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
980,28 Sep 2022,VTU-090,NFCKN7782,2022-09-28 23:35:30,28/09/2022 23:35:51,00:00:21,00:00:21,PokaYoke,CV Mtg M10 bolt by DC tool,21.0,988,2022-09-28 23:35:30,2022-09-28 23:29:40,5,17.0,8.0
981,28 Sep 2022,VTU-080,NFCKN7784,2022-09-28 23:37:52,28/09/2022 23:38:12,00:00:20,00:00:20,PokaYoke,VTU to CV joint stage,20.0,989,2022-09-28 23:37:52,2022-09-28 23:22:50,15,17.0,8.0
982,28 Sep 2022,VTU-090,NFCKN7783,2022-09-28 23:37:52,28/09/2022 23:38:19,00:00:27,00:00:07,PokaYoke,CV Mtg M10 bolt by DC tool,7.0,990,2022-09-28 23:37:52,2022-09-28 23:35:30,2,17.0,8.0
983,28 Sep 2022,VTU-080,NFCKN7784,2022-09-28 23:40:12,28/09/2022 23:40:33,00:00:21,00:00:21,PokaYoke,Interlock CV M8 Bolt,21.0,991,2022-09-28 23:40:12,2022-09-28 23:37:52,2,17.0,8.0
984,28 Sep 2022,VTU-110,NFCKN7782,2022-09-28 23:42:32,28/09/2022 23:42:45,00:00:13,00:00:13,Line stopped due to Emergency Call,Line stopped due to Emergency Call,13.0,992,2022-09-28 23:42:32,2022-09-28 23:32:33,9,17.0,8.0

In [46]:
#set Time_Since_Morning , Time_Since_Shift_Start to int
# new_df['Time_Since_Morning'] = new_df['Time_Since_Morning'].astype(int)
# new_df['Time_Since_Shift_Start'] = new_df['Time_Since_Shift_Start'].astype(int)
# new_df

In [47]:
#Add 24 to Time_Since_Shift_Start if Time_Since_Shift_Start is negative
# new_df.loc[new_df['Time_Since_Shift_Start'] < 0, 'Time_Since_Shift_Start'] = new_df['Time_Since_Shift_Start'] + 24
# new_df

In [48]:
new_df

,Date,Station_Name,Serial_No,Stop_Time,Resume_Time,Duration,ActualLineLoss,Stop_Reason,Remarks,ActualLineLoss_secs,index,Time,Stop_1,Timesince_Previous_Stop,Time_Since_Morning,Time_Since_Shift_Start
1,27 Sep 2022,VTU-110,NFBHB7137,2022-09-27 06:59:38,27/09/2022 06:59:54,00:00:16,00:00:16,Line stopped due to Emergency Call,Line stopped due to Emergency Call,16.0,5,2022-09-27 06:59:38,2022-09-27 06:52:57,6,0.0,0.0
2,27 Sep 2022,VTU-060,NFANA7141,2022-09-27 06:59:57,27/09/2022 07:00:57,00:01:00,00:01:00,PokaYoke,M12 plug Interlock With Conveyor,60.0,6,2022-09-27 06:59:57,2022-09-27 06:56:05,3,0.0,0.0
4,27 Sep 2022,VTU-110,NFANA7138,2022-09-27 07:04:10,27/09/2022 07:04:26,00:00:16,00:00:16,Line stopped due to Emergency Call,Line stopped due to Emergency Call,16.0,9,2022-09-27 07:04:10,2022-09-27 07:00:13,3,1.0,1.0
5,27 Sep 2022,VTU-080,NFANA7141,2022-09-27 07:06:29,27/09/2022 07:07:10,00:00:41,00:00:24,Quality data not saved,Main part SerialNo. not scanned on the station,24.0,10,2022-09-27 07:06:29,2022-09-27 06:56:04,10,1.0,1.0
6,27 Sep 2022,VTU-090,NFDKR7143,2022-09-27 07:06:29,27/09/2022 07:06:46,00:00:17,00:00:17,Quality data not saved,Main part SerialNo. not scanned on the station,17.0,11,2022-09-27 07:06:29,2022-09-27 06:56:04,10,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
980,28 Sep 2022,VTU-090,NFCKN7782,2022-09-28 23:35:30,28/09/2022 23:35:51,00:00:21,00:00:21,PokaYoke,CV Mtg M10 bolt by DC tool,21.0,988,2022-09-28 23:35:30,2022-09-28 23:29:40,5,17.0,8.0
981,28 Sep 2022,VTU-080,NFCKN7784,2022-09-28 23:37:52,28/09/2022 23:38:12,00:00:20,00:00:20,PokaYoke,VTU to CV joint stage,20.0,989,2022-09-28 23:37:52,2022-09-28 23:22:50,15,17.0,8.0
982,28 Sep 2022,VTU-090,NFCKN7783,2022-09-28 23:37:52,28/09/2022 23:38:19,00:00:27,00:00:07,PokaYoke,CV Mtg M10 bolt by DC tool,7.0,990,2022-09-28 23:37:52,2022-09-28 23:35:30,2,17.0,8.0
983,28 Sep 2022,VTU-080,NFCKN7784,2022-09-28 23:40:12,28/09/2022 23:40:33,00:00:21,00:00:21,PokaYoke,Interlock CV M8 Bolt,21.0,991,2022-09-28 23:40:12,2022-09-28 23:37:52,2,17.0,8.0
984,28 Sep 2022,VTU-110,NFCKN7782,2022-09-28 23:42:32,28/09/2022 23:42:45,00:00:13,00:00:13,Line stopped due to Emergency Call,Line stopped due to Emergency Call,13.0,992,2022-09-28 23:42:32,2022-09-28 23:32:33,9,17.0,8.0

In [49]:
#if Time_Since Morning is negative, add 24 to Time_Since_Morning
new_df.loc[new_df['Time_Since_Morning'] < 0, 'Time_Since_Morning'] = 12-abs(new_df['Time_Since_Morning']) + 12
new_df

,Date,Station_Name,Serial_No,Stop_Time,Resume_Time,Duration,ActualLineLoss,Stop_Reason,Remarks,ActualLineLoss_secs,index,Time,Stop_1,Timesince_Previous_Stop,Time_Since_Morning,Time_Since_Shift_Start
1,27 Sep 2022,VTU-110,NFBHB7137,2022-09-27 06:59:38,27/09/2022 06:59:54,00:00:16,00:00:16,Line stopped due to Emergency Call,Line stopped due to Emergency Call,16.0,5,2022-09-27 06:59:38,2022-09-27 06:52:57,6,0.0,0.0
2,27 Sep 2022,VTU-060,NFANA7141,2022-09-27 06:59:57,27/09/2022 07:00:57,00:01:00,00:01:00,PokaYoke,M12 plug Interlock With Conveyor,60.0,6,2022-09-27 06:59:57,2022-09-27 06:56:05,3,0.0,0.0
4,27 Sep 2022,VTU-110,NFANA7138,2022-09-27 07:04:10,27/09/2022 07:04:26,00:00:16,00:00:16,Line stopped due to Emergency Call,Line stopped due to Emergency Call,16.0,9,2022-09-27 07:04:10,2022-09-27 07:00:13,3,1.0,1.0
5,27 Sep 2022,VTU-080,NFANA7141,2022-09-27 07:06:29,27/09/2022 07:07:10,00:00:41,00:00:24,Quality data not saved,Main part SerialNo. not scanned on the station,24.0,10,2022-09-27 07:06:29,2022-09-27 06:56:04,10,1.0,1.0
6,27 Sep 2022,VTU-090,NFDKR7143,2022-09-27 07:06:29,27/09/2022 07:06:46,00:00:17,00:00:17,Quality data not saved,Main part SerialNo. not scanned on the station,17.0,11,2022-09-27 07:06:29,2022-09-27 06:56:04,10,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
980,28 Sep 2022,VTU-090,NFCKN7782,2022-09-28 23:35:30,28/09/2022 23:35:51,00:00:21,00:00:21,PokaYoke,CV Mtg M10 bolt by DC tool,21.0,988,2022-09-28 23:35:30,2022-09-28 23:29:40,5,17.0,8.0
981,28 Sep 2022,VTU-080,NFCKN7784,2022-09-28 23:37:52,28/09/2022 23:38:12,00:00:20,00:00:20,PokaYoke,VTU to CV joint stage,20.0,989,2022-09-28 23:37:52,2022-09-28 23:22:50,15,17.0,8.0
982,28 Sep 2022,VTU-090,NFCKN7783,2022-09-28 23:37:52,28/09/2022 23:38:19,00:00:27,00:00:07,PokaYoke,CV Mtg M10 bolt by DC tool,7.0,990,2022-09-28 23:37:52,2022-09-28 23:35:30,2,17.0,8.0
983,28 Sep 2022,VTU-080,NFCKN7784,2022-09-28 23:40:12,28/09/2022 23:40:33,00:00:21,00:00:21,PokaYoke,Interlock CV M8 Bolt,21.0,991,2022-09-28 23:40:12,2022-09-28 23:37:52,2,17.0,8.0
984,28 Sep 2022,VTU-110,NFCKN7782,2022-09-28 23:42:32,28/09/2022 23:42:45,00:00:13,00:00:13,Line stopped due to Emergency Call,Line stopped due to Emergency Call,13.0,992,2022-09-28 23:42:32,2022-09-28 23:32:33,9,17.0,8.0

In [50]:
# new_df['Resume_Time'] = pd.to_datetime(new_df['Resume_Time'])

In [51]:
# generate normal entries
#first calculate number of unique dates
num_dates = new_df['Date'].nunique()
dates = new_df['Date'].unique()
#calculate min stop time max stop time for each date
min_stop_time = new_df.groupby('Date')['Stop_Time'].min()
max_stop_time = new_df.groupby('Date')['Stop_Time'].max()
min_stop_time

Date
27 Sep 2022   2022-09-27 06:59:38
28 Sep 2022   2022-09-28 06:52:58
Name: Stop_Time, dtype: datetime64[ns]

In [52]:
# #get max from max_stop_time
# max_stop_t = max_stop_time.max()
# max_stop_t

In [53]:
#generate df with all dates with entries between min_stop_time - 10 mins and max_stop_time + 10 mins at a difference of 10 minute
nf = pd.DataFrame()
for i in range(num_dates):
    date = dates[i]
    min_time = min_stop_time[date] - pd.Timedelta(minutes=10)
    max_time = max_stop_time[date] + pd.Timedelta(minutes=10)
    jf = pd.DataFrame(pd.date_range(min_time, max_time, freq='10min',inclusive = 'both'), columns=['Time'])
    jf['Time_1'] = jf['Time'].shift(1)
    jf['Timesince_Previous_Stop'] = (jf['Time'] - jf['Time_1']).dt.total_seconds()//60
    jf.dropna(inplace=True)
    jf['Timesince_Previous_Stop'] = jf['Timesince_Previous_Stop'].astype(int)
    jf['Date1'] = pd.to_datetime(jf['Time']).dt.date
    #create Column Morning_Time using Date1 and time 07:00:00
    jf['Morning_Time'] = pd.to_datetime(jf['Date1'].astype(str) + ' ' + morning_time.strftime('%H:%M:%S'))
    #create Column Morning_Shift_Time using Date1 and time 07:00:00
    jf['Morning_Shift_Time'] = pd.to_datetime(jf['Date1'].astype(str) + ' ' + morning_shift_time.strftime('%H:%M:%S'))
    #create Column Evening_Shift_Time using Date1 and time 15:30:00
    jf['Evening_Shift_Time'] = pd.to_datetime(jf['Date1'].astype(str) + ' ' + evening_shift_time.strftime('%H:%M:%S'))
    #create Column Time_Since_Morning using Time and Morning_Time in hours
    jf['Time_Since_Morning'] = (jf['Time'] - jf['Morning_Time']).dt.total_seconds()//3600
    #create columne Time_Since_Shift_Start using select_time function 
    # #create Column Time_Since_Morning_Shift using Time and Morning_Shift_Time in hours
    jf['Time_Since_Morning_Shift'] = (jf['Time'] - jf['Morning_Shift_Time']).dt.total_seconds()//3600
    # #create Column Time_Since_Evening_Shift using Time and Evening_Shift_Time in hours
    jf['Time_Since_Evening_Shift'] = (jf['Time'] - jf['Evening_Shift_Time']).dt.total_seconds()//3600
    jf['Time_Since_Shift_Start'] = jf.apply(lambda x: select(x['Time_Since_Morning_Shift'], x['Time_Since_Evening_Shift']), axis=1)
    jf.drop(columns=['Morning_Time', 'Morning_Shift_Time', 'Evening_Shift_Time', 'Time_Since_Morning_Shift', 'Time_Since_Evening_Shift','Date1','Time_1'], inplace=True)
    
    nf = nf.append(jf)
    
nf['Date'] = pd.to_datetime(nf['Time']).dt.date
nf['Stop_Reason'] = 'Normal'
nf['Remarks'] = 'Normal'
nf['Station_Name'] = 'All'
nf['Time_Since_Morning'] = nf['Time_Since_Morning'].astype(int)
nf['Time_Since_Shift_Start'] = nf['Time_Since_Shift_Start'].astype(int)
#rename Time column to Stop_Time
nf.rename(columns={'Time':'Stop_Time'}, inplace=True)
nf

<ipython-input-53-faab5f4aeec5>:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  nf = nf.append(jf)
<ipython-input-53-faab5f4aeec5>:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  nf = nf.append(jf)

,Stop_Time,Timesince_Previous_Stop,Time_Since_Morning,Time_Since_Shift_Start,Date,Stop_Reason,Remarks,Station_Name
1,2022-09-27 06:59:38,10,0,0,2022-09-27,Normal,Normal,All
2,2022-09-27 07:09:38,10,1,1,2022-09-27,Normal,Normal,All
3,2022-09-27 07:19:38,10,1,1,2022-09-27,Normal,Normal,All
4,2022-09-27 07:29:38,10,1,1,2022-09-27,Normal,Normal,All
5,2022-09-27 07:39:38,10,1,1,2022-09-27,Normal,Normal,All
...,...,...,...,...,...,...,...,...
98,2022-09-28 23:02:58,10,17,7,2022-09-28,Normal,Normal,All
99,2022-09-28 23:12:58,10,17,7,2022-09-28,Normal,Normal,All
100,2022-09-28 23:22:58,10,17,7,2022-09-28,Normal,Normal,All
101,2022-09-28 23:32:58,10,17,8,2022-09-28,Normal,Normal,All
102,2022-09-28 23:42:58,10,17,8,2022-09-28,Normal,Normal,All

In [54]:
#add 12 + (12 -abs(Time_Since_Morning)) to Time_Since_Shift_Start if Time_Since_Shift_Start is negative
nf.loc[nf['Time_Since_Shift_Start'] < 0, 'Time_Since_Shift_Start'] = 12 + (12 - abs(nf['Time_Since_Shift_Start']))

In [55]:
# #shift Resume_Time by 1 row
# new_df['Resume_shift'] = new_df['Resume_Time'].shift(1)
# #calculate Time_Since_Resume using Stop_Time and Resume_shift
# new_df['Time_Between_Stops'] = (new_df['Stop_Time'] - new_df['Resume_shift']).dt.total_seconds()//60
# new_df, new_df['Time_Between_Stops'].min(), new_df['Time_Between_Stops'].max(), new_df['Time_Between_Stops'].mean()

In [56]:
# new_df[new_df['Time_Between_Stops'] < 0]

In [57]:
useful_cols = ['Date','Stop','Stop_Time','Station_Name','Stop_Reason','Remarks','Timesince_Previous_Stop','Time_Since_Morning','Time_Since_Shift_Start']

In [58]:
nf['Stop'] = 0
new_df['Stop'] = 1

In [59]:
new_df

,Date,Station_Name,Serial_No,Stop_Time,Resume_Time,Duration,ActualLineLoss,Stop_Reason,Remarks,ActualLineLoss_secs,index,Time,Stop_1,Timesince_Previous_Stop,Time_Since_Morning,Time_Since_Shift_Start,Stop
1,27 Sep 2022,VTU-110,NFBHB7137,2022-09-27 06:59:38,27/09/2022 06:59:54,00:00:16,00:00:16,Line stopped due to Emergency Call,Line stopped due to Emergency Call,16.0,5,2022-09-27 06:59:38,2022-09-27 06:52:57,6,0.0,0.0,1
2,27 Sep 2022,VTU-060,NFANA7141,2022-09-27 06:59:57,27/09/2022 07:00:57,00:01:00,00:01:00,PokaYoke,M12 plug Interlock With Conveyor,60.0,6,2022-09-27 06:59:57,2022-09-27 06:56:05,3,0.0,0.0,1
4,27 Sep 2022,VTU-110,NFANA7138,2022-09-27 07:04:10,27/09/2022 07:04:26,00:00:16,00:00:16,Line stopped due to Emergency Call,Line stopped due to Emergency Call,16.0,9,2022-09-27 07:04:10,2022-09-27 07:00:13,3,1.0,1.0,1
5,27 Sep 2022,VTU-080,NFANA7141,2022-09-27 07:06:29,27/09/2022 07:07:10,00:00:41,00:00:24,Quality data not saved,Main part SerialNo. not scanned on the station,24.0,10,2022-09-27 07:06:29,2022-09-27 06:56:04,10,1.0,1.0,1
6,27 Sep 2022,VTU-090,NFDKR7143,2022-09-27 07:06:29,27/09/2022 07:06:46,00:00:17,00:00:17,Quality data not saved,Main part SerialNo. not scanned on the station,17.0,11,2022-09-27 07:06:29,2022-09-27 06:56:04,10,1.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
980,28 Sep 2022,VTU-090,NFCKN7782,2022-09-28 23:35:30,28/09/2022 23:35:51,00:00:21,00:00:21,PokaYoke,CV Mtg M10 bolt by DC tool,21.0,988,2022-09-28 23:35:30,2022-09-28 23:29:40,5,17.0,8.0,1
981,28 Sep 2022,VTU-080,NFCKN7784,2022-09-28 23:37:52,28/09/2022 23:38:12,00:00:20,00:00:20,PokaYoke,VTU to CV joint stage,20.0,989,2022-09-28 23:37:52,2022-09-28 23:22:50,15,17.0,8.0,1
982,28 Sep 2022,VTU-090,NFCKN7783,2022-09-28 23:37:52,28/09/2022 23:38:19,00:00:27,00:00:07,PokaYoke,CV Mtg M10 bolt by DC tool,7.0,990,2022-09-28 23:37:52,2022-09-28 23:35:30,2,17.0,8.0,1
983,28 Sep 2022,VTU-080,NFCKN7784,2022-09-28 23:40:12,28/09/2022 23:40:33,00:00:21,00:00:21,PokaYoke,Interlock CV M8 Bolt,21.0,991,2022-09-28 23:40:12,2022-09-28 23:37:52,2,17.0,8.0,1
984,28 Sep 2022,VTU-110,NFCKN7782,2022-09-28 23:42:32,28/09/2022 23:42:45,00:00:13,00:00:13,Line stopped due to Emergency Call,Line stopped due to Emergency Call,13.0,992,2022-09-28 23:42:32,2022-09-28 23:32:33,9,17.0,8.0,1

In [60]:
neg = nf[nf['Time_Since_Morning']<0]
neg

Empty DataFrame
Columns: [Stop_Time, Timesince_Previous_Stop, Time_Since_Morning, Time_Since_Shift_Start, Date, Stop_Reason, Remarks, Station_Name, Stop]
Index: []

In [61]:
#add 12 + (12 -abs(Time_Since_Morning)) to Time_Since_Morning if Time_Since_Morning is negative
nf.loc[nf['Time_Since_Morning'] < 0, 'Time_Since_Morning'] = 12 + (12 - abs(nf['Time_Since_Morning']))

In [62]:
nf = nf[useful_cols]
new_df = new_df[useful_cols]
new_df = new_df.append(nf)
new_df

<ipython-input-62-e61630a75b5a>:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append(nf)

,Date,Stop,Stop_Time,Station_Name,Stop_Reason,Remarks,Timesince_Previous_Stop,Time_Since_Morning,Time_Since_Shift_Start
1,27 Sep 2022,1,2022-09-27 06:59:38,VTU-110,Line stopped due to Emergency Call,Line stopped due to Emergency Call,6,0.0,0.0
2,27 Sep 2022,1,2022-09-27 06:59:57,VTU-060,PokaYoke,M12 plug Interlock With Conveyor,3,0.0,0.0
4,27 Sep 2022,1,2022-09-27 07:04:10,VTU-110,Line stopped due to Emergency Call,Line stopped due to Emergency Call,3,1.0,1.0
5,27 Sep 2022,1,2022-09-27 07:06:29,VTU-080,Quality data not saved,Main part SerialNo. not scanned on the station,10,1.0,1.0
6,27 Sep 2022,1,2022-09-27 07:06:29,VTU-090,Quality data not saved,Main part SerialNo. not scanned on the station,10,1.0,1.0
...,...,...,...,...,...,...,...,...,...
98,2022-09-28,0,2022-09-28 23:02:58,All,Normal,Normal,10,17.0,7.0
99,2022-09-28,0,2022-09-28 23:12:58,All,Normal,Normal,10,17.0,7.0
100,2022-09-28,0,2022-09-28 23:22:58,All,Normal,Normal,10,17.0,7.0
101,2022-09-28,0,2022-09-28 23:32:58,All,Normal,Normal,10,17.0,8.0
102,2022-09-28,0,2022-09-28 23:42:58,All,Normal,Normal,10,17.0,8.0

In [63]:
#sort new_df values by Stop_Time
new_df.sort_values(by='Stop_Time', inplace=True)
new_df.reset_index(drop=True, inplace=True)

In [64]:
new_df

,Date,Stop,Stop_Time,Station_Name,Stop_Reason,Remarks,Timesince_Previous_Stop,Time_Since_Morning,Time_Since_Shift_Start
0,27 Sep 2022,1,2022-09-27 06:59:38,VTU-110,Line stopped due to Emergency Call,Line stopped due to Emergency Call,6,0.0,0.0
1,2022-09-27,0,2022-09-27 06:59:38,All,Normal,Normal,10,0.0,0.0
2,27 Sep 2022,1,2022-09-27 06:59:57,VTU-060,PokaYoke,M12 plug Interlock With Conveyor,3,0.0,0.0
3,27 Sep 2022,1,2022-09-27 07:04:10,VTU-110,Line stopped due to Emergency Call,Line stopped due to Emergency Call,3,1.0,1.0
4,27 Sep 2022,1,2022-09-27 07:06:29,VTU-080,Quality data not saved,Main part SerialNo. not scanned on the station,10,1.0,1.0
...,...,...,...,...,...,...,...,...,...
1103,28 Sep 2022,1,2022-09-28 23:37:52,VTU-090,PokaYoke,CV Mtg M10 bolt by DC tool,2,17.0,8.0
1104,28 Sep 2022,1,2022-09-28 23:37:52,VTU-080,PokaYoke,VTU to CV joint stage,15,17.0,8.0
1105,28 Sep 2022,1,2022-09-28 23:40:12,VTU-080,PokaYoke,Interlock CV M8 Bolt,2,17.0,8.0
1106,28 Sep 2022,1,2022-09-28 23:42:32,VTU-110,Line stopped due to Emergency Call,Line stopped due to Emergency Call,9,17.0,8.0
1107,2022-09-28,0,2022-09-28 23:42:58,All,Normal,Normal,10,17.0,8.0

In [65]:
#List of all Remarks
Remarks = new_df['Remarks'].unique()
num_Remarks = len(Remarks)
#Create a Dictionary of Remarks and name them Remark_1, Remark_2, Remark_3, etc
Remarks_Label = {}
for i in range(num_Remarks):
    Remarks_Label[Remarks[i]] = 'Remark_' + str(i+1)
print(Remarks_Label)
#Replace Remarks with Remark_1, Remark_2, Remark_3, etc
new_df.replace({'Remarks':Remarks_Label}, inplace=True)
#perform same operation on Stop_Reason
Stop_Reason = new_df['Stop_Reason'].unique()
num_Stop_Reason = len(Stop_Reason)
Stop_Reason_label = {}
for i in range(num_Stop_Reason):
    Stop_Reason_label[Stop_Reason[i]] = 'Stop_Reason_' + str(i+1)
print(Stop_Reason_label)
new_df.replace({'Stop_Reason':Stop_Reason_label}, inplace=True)
#perform same operation on Station_Name
Station_Name = new_df['Station_Name'].unique()
num_Station_Name = len(Station_Name)
Station_Name_label = {}
for i in range(num_Station_Name):
    Station_Name_label[Station_Name[i]] = 'Station_Name_' + str(i+1)
print(Station_Name_label)
new_df.replace({'Station_Name':Station_Name_label}, inplace=True)

{'Line stopped due to Emergency Call': 'Remark_1', 'Normal': 'Remark_2', 'M12 plug  Interlock With Conveyor': 'Remark_3', 'Main part SerialNo. not scanned on the station': 'Remark_4', 'VTU to CV joint stage': 'Remark_5', 'CV Mtg M10 bolt by DC tool ': 'Remark_6', 'Interlock CV M8 Bolt': 'Remark_7', 'Grease nipple': 'Remark_8', 'DC Plunger Support with compfor ': 'Remark_9', 'RLF coupling ': 'Remark_10', 'Pivot bolt  . Interlock With Conveyor.': 'Remark_11', 'Rocker Arm bolt': 'Remark_12', 'Cyl. front side mtg Bolts': 'Remark_13', 'M20 (QL) Plug for M-star & Dhruv.Interlock with Conveyor': 'Remark_14'}
{'Line stopped due to Emergency Call': 'Stop_Reason_1', 'Normal': 'Stop_Reason_2', 'PokaYoke': 'Stop_Reason_3', 'Quality data not saved': 'Stop_Reason_4'}
{'VTU-110': 'Station_Name_1', 'All': 'Station_Name_2', 'VTU-060': 'Station_Name_3', 'VTU-080': 'Station_Name_4', 'VTU-090': 'Station_Name_5', 'VTU-100': 'Station_Name_6', 'VTU-070': 'Station_Name_7', 'VTU-030': 'Station_Name_8', 'VTU-040': 'Station_Name_9'}

In [66]:
gf = new_df.copy()
#find number of occurences of each Remark
gf['Remarks'].value_counts()
#get min and max Stop_Time for each Remark
gf.groupby('Remarks')['Stop_Time'].agg(['min','max'])
#avg Time_Since_Previous_Stop for each Remark
gf.groupby('Remarks')['Timesince_Previous_Stop'].mean()
#create dictionary of Remarks and their mean Time_Since_Previous_Stop
Remarks_dict = gf.groupby('Remarks')['Timesince_Previous_Stop'].mean().to_dict()
#same for Stop_Reason
Stop_Reason_dict = gf.groupby('Stop_Reason')['Timesince_Previous_Stop'].mean().to_dict()
#create column Time_Since_Previous_Remark using Remarks_dict
gf['Time_Since_Previous_Remark'] = gf['Remarks'].map(Remarks_dict)
#create column Time_Since_Previous_Stop_Reason using Stop_Reason_dict
gf['Time_Since_Previous_Stop_Reason'] = gf['Stop_Reason'].map(Stop_Reason_dict)

gf

,Date,Stop,Stop_Time,Station_Name,Stop_Reason,Remarks,Timesince_Previous_Stop,Time_Since_Morning,Time_Since_Shift_Start,Time_Since_Previous_Remark,Time_Since_Previous_Stop_Reason
0,27 Sep 2022,1,2022-09-27 06:59:38,Station_Name_1,Stop_Reason_1,Remark_1,6,0.0,0.0,6.651899,6.651899
1,2022-09-27,0,2022-09-27 06:59:38,Station_Name_2,Stop_Reason_2,Remark_2,10,0.0,0.0,10.000000,10.000000
2,27 Sep 2022,1,2022-09-27 06:59:57,Station_Name_3,Stop_Reason_3,Remark_3,3,0.0,0.0,52.571429,25.190751
3,27 Sep 2022,1,2022-09-27 07:04:10,Station_Name_1,Stop_Reason_1,Remark_1,3,1.0,1.0,6.651899,6.651899
4,27 Sep 2022,1,2022-09-27 07:06:29,Station_Name_4,Stop_Reason_4,Remark_4,10,1.0,1.0,28.805288,28.805288
...,...,...,...,...,...,...,...,...,...,...,...
1103,28 Sep 2022,1,2022-09-28 23:37:52,Station_Name_5,Stop_Reason_3,Remark_6,2,17.0,8.0,23.848485,25.190751
1104,28 Sep 2022,1,2022-09-28 23:37:52,Station_Name_4,Stop_Reason_3,Remark_5,15,17.0,8.0,14.406250,25.190751
1105,28 Sep 2022,1,2022-09-28 23:40:12,Station_Name_4,Stop_Reason_3,Remark_7,2,17.0,8.0,26.100000,25.190751
1106,28 Sep 2022,1,2022-09-28 23:42:32,Station_Name_1,Stop_Reason_1,Remark_1,9,17.0,8.0,6.651899,6.651899
1107,2022-09-28,0,2022-09-28 23:42:58,Station_Name_2,Stop_Reason_2,Remark_2,10,17.0,8.0,10.000000,10.000000

In [67]:
new_df.isna().sum()

Date                       0
Stop                       0
Stop_Time                  0
Station_Name               0
Stop_Reason                0
Remarks                    0
Timesince_Previous_Stop    0
Time_Since_Morning         0
Time_Since_Shift_Start     0
dtype: int64

In [68]:
#add 12 + (12 -abs(Time_Since_Morning)) to Time_Since_Morning if Time_Since_Morning is negative
gf.loc[gf['Time_Since_Morning'] < 0, 'Time_Since_Morning'] = 12 + (12 - abs(gf['Time_Since_Morning']))
# neg = gf[gf['Time_Since_Shift_Start']<0]
# neg

In [69]:
gf

,Date,Stop,Stop_Time,Station_Name,Stop_Reason,Remarks,Timesince_Previous_Stop,Time_Since_Morning,Time_Since_Shift_Start,Time_Since_Previous_Remark,Time_Since_Previous_Stop_Reason
0,27 Sep 2022,1,2022-09-27 06:59:38,Station_Name_1,Stop_Reason_1,Remark_1,6,0.0,0.0,6.651899,6.651899
1,2022-09-27,0,2022-09-27 06:59:38,Station_Name_2,Stop_Reason_2,Remark_2,10,0.0,0.0,10.000000,10.000000
2,27 Sep 2022,1,2022-09-27 06:59:57,Station_Name_3,Stop_Reason_3,Remark_3,3,0.0,0.0,52.571429,25.190751
3,27 Sep 2022,1,2022-09-27 07:04:10,Station_Name_1,Stop_Reason_1,Remark_1,3,1.0,1.0,6.651899,6.651899
4,27 Sep 2022,1,2022-09-27 07:06:29,Station_Name_4,Stop_Reason_4,Remark_4,10,1.0,1.0,28.805288,28.805288
...,...,...,...,...,...,...,...,...,...,...,...
1103,28 Sep 2022,1,2022-09-28 23:37:52,Station_Name_5,Stop_Reason_3,Remark_6,2,17.0,8.0,23.848485,25.190751
1104,28 Sep 2022,1,2022-09-28 23:37:52,Station_Name_4,Stop_Reason_3,Remark_5,15,17.0,8.0,14.406250,25.190751
1105,28 Sep 2022,1,2022-09-28 23:40:12,Station_Name_4,Stop_Reason_3,Remark_7,2,17.0,8.0,26.100000,25.190751
1106,28 Sep 2022,1,2022-09-28 23:42:32,Station_Name_1,Stop_Reason_1,Remark_1,9,17.0,8.0,6.651899,6.651899
1107,2022-09-28,0,2022-09-28 23:42:58,Station_Name_2,Stop_Reason_2,Remark_2,10,17.0,8.0,10.000000,10.000000

In [70]:
# gf.to_csv(r'C:\Users\priya\Projects\new_working\new_df.csv', index=False)

In [71]:
gf.describe()

,Stop,Timesince_Previous_Stop,Time_Since_Morning,Time_Since_Shift_Start,Time_Since_Previous_Remark,Time_Since_Previous_Stop_Reason
count,1108.000000,1108.000000,1108.000000,1108.000000,1108.000000,1108.000000
mean,0.816787,18.477437,8.997292,4.266245,18.477437,18.477437
std,0.387016,45.556763,4.578631,2.680260,11.108790,10.011231
min,0.000000,1.000000,0.000000,0.000000,4.000000,6.651899
25%,1.000000,3.000000,6.000000,2.000000,6.651899,6.651899
50%,1.000000,9.500000,9.000000,4.000000,14.406250,25.190751
75%,1.000000,13.000000,12.000000,7.000000,28.805288,28.805288
max,1.000000,525.000000,17.000000,9.000000,52.571429,28.805288

PRINT LABEL ENCODINGS

In [72]:
#print Stop_Reason Dictionary
print("Stop_Reason_label")
for i in Stop_Reason_label:
    print(f" {i} : {Stop_Reason_label[i]}")
#print Remarks Dictionary
print("\n\nRemarks_label")
for i in Remarks_Label:
    print(f" {i} : {Remarks_Label[i]}")

Stop_Reason_label
 Line stopped due to Emergency Call : Stop_Reason_1
 Normal : Stop_Reason_2
 PokaYoke : Stop_Reason_3
 Quality data not saved : Stop_Reason_4


Remarks_label
 Line stopped due to Emergency Call : Remark_1
 Normal : Remark_2
 M12 plug  Interlock With Conveyor : Remark_3
 Main part SerialNo. not scanned on the station : Remark_4
 VTU to CV joint stage : Remark_5
 CV Mtg M10 bolt by DC tool  : Remark_6
 Interlock CV M8 Bolt : Remark_7
 Grease nipple : Remark_8
 DC Plunger Support with compfor  : Remark_9
 RLF coupling  : Remark_10
 Pivot bolt  . Interlock With Conveyor. : Remark_11
 Rocker Arm bolt : Remark_12
 Cyl. front side mtg Bolts : Remark_13
 M20 (QL) Plug for M-star & Dhruv.Interlock with Conveyor : Remark_14

In [73]:

print("\n\nStation_Name_label")
for i in Station_Name_label:
    print(f" {i} : {Station_Name_label[i]}")

Station_Name_label
 VTU-110 : Station_Name_1
 All : Station_Name_2
 VTU-060 : Station_Name_3
 VTU-080 : Station_Name_4
 VTU-090 : Station_Name_5
 VTU-100 : Station_Name_6
 VTU-070 : Station_Name_7
 VTU-030 : Station_Name_8
 VTU-040 : Station_Name_9

In [74]:
ef = gf.copy()

In [75]:
#Create column Station_Name + Stop_Reason + Remarks
ef['Combination'] = gf['Station_Name'] + '-' + gf['Stop_Reason'] + '-' + gf['Remarks']
ef

,Date,Stop,Stop_Time,Station_Name,Stop_Reason,Remarks,Timesince_Previous_Stop,Time_Since_Morning,Time_Since_Shift_Start,Time_Since_Previous_Remark,Time_Since_Previous_Stop_Reason,Combination
0,27 Sep 2022,1,2022-09-27 06:59:38,Station_Name_1,Stop_Reason_1,Remark_1,6,0.0,0.0,6.651899,6.651899,Station_Name_1-Stop_Reason_1-Remark_1
1,2022-09-27,0,2022-09-27 06:59:38,Station_Name_2,Stop_Reason_2,Remark_2,10,0.0,0.0,10.000000,10.000000,Station_Name_2-Stop_Reason_2-Remark_2
2,27 Sep 2022,1,2022-09-27 06:59:57,Station_Name_3,Stop_Reason_3,Remark_3,3,0.0,0.0,52.571429,25.190751,Station_Name_3-Stop_Reason_3-Remark_3
3,27 Sep 2022,1,2022-09-27 07:04:10,Station_Name_1,Stop_Reason_1,Remark_1,3,1.0,1.0,6.651899,6.651899,Station_Name_1-Stop_Reason_1-Remark_1
4,27 Sep 2022,1,2022-09-27 07:06:29,Station_Name_4,Stop_Reason_4,Remark_4,10,1.0,1.0,28.805288,28.805288,Station_Name_4-Stop_Reason_4-Remark_4
...,...,...,...,...,...,...,...,...,...,...,...,...
1103,28 Sep 2022,1,2022-09-28 23:37:52,Station_Name_5,Stop_Reason_3,Remark_6,2,17.0,8.0,23.848485,25.190751,Station_Name_5-Stop_Reason_3-Remark_6
1104,28 Sep 2022,1,2022-09-28 23:37:52,Station_Name_4,Stop_Reason_3,Remark_5,15,17.0,8.0,14.406250,25.190751,Station_Name_4-Stop_Reason_3-Remark_5
1105,28 Sep 2022,1,2022-09-28 23:40:12,Station_Name_4,Stop_Reason_3,Remark_7,2,17.0,8.0,26.100000,25.190751,Station_Name_4-Stop_Reason_3-Remark_7
1106,28 Sep 2022,1,2022-09-28 23:42:32,Station_Name_1,Stop_Reason_1,Remark_1,9,17.0,8.0,6.651899,6.651899,Station_Name_1-Stop_Reason_1-Remark_1
1107,2022-09-28,0,2022-09-28 23:42:58,Station_Name_2,Stop_Reason_2,Remark_2,10,17.0,8.0,10.000000,10.000000,Station_Name_2-Stop_Reason_2-Remark_2

In [76]:
#create dummy variables for Combination
ef = pd.get_dummies(ef, columns=['Combination'],prefix_sep = '-')
ef

,Date,Stop,Stop_Time,Station_Name,Stop_Reason,Remarks,Timesince_Previous_Stop,Time_Since_Morning,Time_Since_Shift_Start,Time_Since_Previous_Remark,...,Combination-Station_Name_5-Stop_Reason_3-Remark_6,Combination-Station_Name_5-Stop_Reason_4-Remark_4,Combination-Station_Name_6-Stop_Reason_4-Remark_4,Combination-Station_Name_7-Stop_Reason_4-Remark_4,Combination-Station_Name_8-Stop_Reason_3-Remark_12,Combination-Station_Name_8-Stop_Reason_3-Remark_14,Combination-Station_Name_8-Stop_Reason_4-Remark_4,Combination-Station_Name_9-Stop_Reason_3-Remark_11,Combination-Station_Name_9-Stop_Reason_3-Remark_9,Combination-Station_Name_9-Stop_Reason_4-Remark_4
0,27 Sep 2022,1,2022-09-27 06:59:38,Station_Name_1,Stop_Reason_1,Remark_1,6,0.0,0.0,6.651899,...,0,0,0,0,0,0,0,0,0,0
1,2022-09-27,0,2022-09-27 06:59:38,Station_Name_2,Stop_Reason_2,Remark_2,10,0.0,0.0,10.000000,...,0,0,0,0,0,0,0,0,0,0
2,27 Sep 2022,1,2022-09-27 06:59:57,Station_Name_3,Stop_Reason_3,Remark_3,3,0.0,0.0,52.571429,...,0,0,0,0,0,0,0,0,0,0
3,27 Sep 2022,1,2022-09-27 07:04:10,Station_Name_1,Stop_Reason_1,Remark_1,3,1.0,1.0,6.651899,...,0,0,0,0,0,0,0,0,0,0
4,27 Sep 2022,1,2022-09-27 07:06:29,Station_Name_4,Stop_Reason_4,Remark_4,10,1.0,1.0,28.805288,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1103,28 Sep 2022,1,2022-09-28 23:37:52,Station_Name_5,Stop_Reason_3,Remark_6,2,17.0,8.0,23.848485,...,1,0,0,0,0,0,0,0,0,0
1104,28 Sep 2022,1,2022-09-28 23:37:52,Station_Name_4,Stop_Reason_3,Remark_5,15,17.0,8.0,14.406250,...,0,0,0,0,0,0,0,0,0,0
1105,28 Sep 2022,1,2022-09-28 23:40:12,Station_Name_4,Stop_Reason_3,Remark_7,2,17.0,8.0,26.100000,...,0,0,0,0,0,0,0,0,0,0
1106,28 Sep 2022,1,2022-09-28 23:42:32,Station_Name_1,Stop_Reason_1,Remark_1,9,17.0,8.0,6.651899,...,0,0,0,0,0,0,0,0,0,0
1107,2022-09-28,0,2022-09-28 23:42:58,Station_Name_2,Stop_Reason_2,Remark_2,10,17.0,8.0,10.000000,...,0,0,0,0,0,0,0,0,0,0

In [77]:
#remove Combination- from column names
ef.columns = ef.columns.str.replace('Combination-','')

In [78]:
#Set Stop_Time to Hour:00:00
ef['Stop_Time'] = ef['Stop_Time'].dt.floor('H')
ef

,Date,Stop,Stop_Time,Station_Name,Stop_Reason,Remarks,Timesince_Previous_Stop,Time_Since_Morning,Time_Since_Shift_Start,Time_Since_Previous_Remark,...,Station_Name_5-Stop_Reason_3-Remark_6,Station_Name_5-Stop_Reason_4-Remark_4,Station_Name_6-Stop_Reason_4-Remark_4,Station_Name_7-Stop_Reason_4-Remark_4,Station_Name_8-Stop_Reason_3-Remark_12,Station_Name_8-Stop_Reason_3-Remark_14,Station_Name_8-Stop_Reason_4-Remark_4,Station_Name_9-Stop_Reason_3-Remark_11,Station_Name_9-Stop_Reason_3-Remark_9,Station_Name_9-Stop_Reason_4-Remark_4
0,27 Sep 2022,1,2022-09-27 06:00:00,Station_Name_1,Stop_Reason_1,Remark_1,6,0.0,0.0,6.651899,...,0,0,0,0,0,0,0,0,0,0
1,2022-09-27,0,2022-09-27 06:00:00,Station_Name_2,Stop_Reason_2,Remark_2,10,0.0,0.0,10.000000,...,0,0,0,0,0,0,0,0,0,0
2,27 Sep 2022,1,2022-09-27 06:00:00,Station_Name_3,Stop_Reason_3,Remark_3,3,0.0,0.0,52.571429,...,0,0,0,0,0,0,0,0,0,0
3,27 Sep 2022,1,2022-09-27 07:00:00,Station_Name_1,Stop_Reason_1,Remark_1,3,1.0,1.0,6.651899,...,0,0,0,0,0,0,0,0,0,0
4,27 Sep 2022,1,2022-09-27 07:00:00,Station_Name_4,Stop_Reason_4,Remark_4,10,1.0,1.0,28.805288,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1103,28 Sep 2022,1,2022-09-28 23:00:00,Station_Name_5,Stop_Reason_3,Remark_6,2,17.0,8.0,23.848485,...,1,0,0,0,0,0,0,0,0,0
1104,28 Sep 2022,1,2022-09-28 23:00:00,Station_Name_4,Stop_Reason_3,Remark_5,15,17.0,8.0,14.406250,...,0,0,0,0,0,0,0,0,0,0
1105,28 Sep 2022,1,2022-09-28 23:00:00,Station_Name_4,Stop_Reason_3,Remark_7,2,17.0,8.0,26.100000,...,0,0,0,0,0,0,0,0,0,0
1106,28 Sep 2022,1,2022-09-28 23:00:00,Station_Name_1,Stop_Reason_1,Remark_1,9,17.0,8.0,6.651899,...,0,0,0,0,0,0,0,0,0,0
1107,2022-09-28,0,2022-09-28 23:00:00,Station_Name_2,Stop_Reason_2,Remark_2,10,17.0,8.0,10.000000,...,0,0,0,0,0,0,0,0,0,0

In [79]:
colsname = ['Stop','Date','Station_Name','Stop_Reason','Remarks','Time_Since_Previous_Stop_Reason','Time_Since_Previous_Remark','Timesince_Previous_Stop']
ef.drop(colsname, axis=1, inplace=True)

In [80]:
l1 = ef.columns.to_list()
l1 = l1[3:]
l1
#create dictionary diss where keys l1 and values are 'sum'
diss = {}
for i in l1:
    diss[i] = 'sum'
diss['Time_Since_Shift_Start'] =  'min'
diss

{'Station_Name_1-Stop_Reason_1-Remark_1': 'sum',
 'Station_Name_1-Stop_Reason_3-Remark_8': 'sum',
 'Station_Name_2-Stop_Reason_2-Remark_2': 'sum',
 'Station_Name_3-Stop_Reason_3-Remark_3': 'sum',
 'Station_Name_3-Stop_Reason_4-Remark_4': 'sum',
 'Station_Name_4-Stop_Reason_3-Remark_10': 'sum',
 'Station_Name_4-Stop_Reason_3-Remark_13': 'sum',
 'Station_Name_4-Stop_Reason_3-Remark_5': 'sum',
 'Station_Name_4-Stop_Reason_3-Remark_7': 'sum',
 'Station_Name_4-Stop_Reason_4-Remark_4': 'sum',
 'Station_Name_5-Stop_Reason_3-Remark_6': 'sum',
 'Station_Name_5-Stop_Reason_4-Remark_4': 'sum',
 'Station_Name_6-Stop_Reason_4-Remark_4': 'sum',
 'Station_Name_7-Stop_Reason_4-Remark_4': 'sum',
 'Station_Name_8-Stop_Reason_3-Remark_12': 'sum',
 'Station_Name_8-Stop_Reason_3-Remark_14': 'sum',
 'Station_Name_8-Stop_Reason_4-Remark_4': 'sum',
 'Station_Name_9-Stop_Reason_3-Remark_11': 'sum',
 'Station_Name_9-Stop_Reason_3-Remark_9': 'sum',
 'Station_Name_9-Stop_Reason_4-Remark_4': 'sum',
 'Time_Since_Shift_Start': 'min'}

In [81]:
#groupby Stop_Time and sum all columns except min of Time_Since_Shift_Start
tf = ef.groupby(['Stop_Time','Time_Since_Morning']).agg(diss).reset_index()


# ef = ef.groupby(['Stop_Time','Time_Since_Morning','Time_Since_Shift_Start']).sum()
tf

,Stop_Time,Time_Since_Morning,Station_Name_1-Stop_Reason_1-Remark_1,Station_Name_1-Stop_Reason_3-Remark_8,Station_Name_2-Stop_Reason_2-Remark_2,Station_Name_3-Stop_Reason_3-Remark_3,Station_Name_3-Stop_Reason_4-Remark_4,Station_Name_4-Stop_Reason_3-Remark_10,Station_Name_4-Stop_Reason_3-Remark_13,Station_Name_4-Stop_Reason_3-Remark_5,...,Station_Name_5-Stop_Reason_4-Remark_4,Station_Name_6-Stop_Reason_4-Remark_4,Station_Name_7-Stop_Reason_4-Remark_4,Station_Name_8-Stop_Reason_3-Remark_12,Station_Name_8-Stop_Reason_3-Remark_14,Station_Name_8-Stop_Reason_4-Remark_4,Station_Name_9-Stop_Reason_3-Remark_11,Station_Name_9-Stop_Reason_3-Remark_9,Station_Name_9-Stop_Reason_4-Remark_4,Time_Since_Shift_Start
0,2022-09-27 06:00:00,0.0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
1,2022-09-27 07:00:00,1.0,2,0,6,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1.0
2,2022-09-27 08:00:00,2.0,1,0,6,2,0,0,0,1,...,1,0,0,0,0,0,0,0,0,2.0
3,2022-09-27 09:00:00,3.0,7,2,6,1,3,0,0,2,...,0,1,2,0,0,1,0,0,0,3.0
4,2022-09-27 10:00:00,4.0,5,1,6,0,2,0,0,1,...,0,1,1,0,0,0,0,0,1,4.0
5,2022-09-27 11:00:00,5.0,5,2,6,0,1,0,0,1,...,0,1,0,0,0,1,0,0,1,5.0
6,2022-09-27 12:00:00,6.0,11,0,6,0,4,1,0,1,...,1,0,3,0,0,2,0,1,2,6.0
7,2022-09-27 13:00:00,7.0,13,0,6,1,0,1,0,1,...,1,5,1,0,0,4,1,0,0,7.0
8,2022-09-27 14:00:00,8.0,12,0,6,1,2,0,0,4,...,3,0,1,0,0,0,0,0,0,8.0
9,2022-09-27 15:00:00,9.0,14,1,6,1,5,0,0,1,...,3,1,5,0,0,3,0,0,3,0.0
10,2022-09-27 16:00:00,10.0,13,0,6,0,2,8,0,0,...,0,0,8,0,0,2,0,0,4,0.0
11,2022-09-27 17:00:00,11.0,10,0,6,0,5,3,0,0,...,3,1,0,0,0,4,0,0,1,1.0
12,2022-09-27 18:00:00,12.0,15,1,6,1,4,2,0,1,...,0,3,4,1,0,1,0,0,4,2.0
13,2022-09-27 19:00:00,13.0,9,0,6,0,2,3,0,0,...,0,1,3,0,0,2,0,0,3,3.0
14,2022-09-27 20:00:00,14.0,6,0,6,0,3,1,0,0,...,1,0,1,0,0,1,0,0,2,4.0
15,2022-09-27 21:00:00,15.0,10,0,6,1,2,1,1,1,...,3,2,1,0,0,3,0,1,1,5.0
16,2022-09-27 22:00:00,16.0,11,0,6,1,0,0,0,2,...,6,3,2,0,0,1,0,0,5,6.0
17,2022-09-27 23:00:00,17.0,13,0,4,0,0,0,0,0,...,1,2,5,1,0,6,0,0,1,7.0
18,2022-09-28 06:00:00,0.0,2,0,1,1,0,0,0,0,...,1,1,0,0,0,1,0,0,1,0.0
19,2022-09-28 07:00:00,1.0,7,1,6,1,0,0,0,3,...,3,1,1,0,0,1,0,0,3,1.0
20,2022-09-28 08:00:00,2.0,10,0,6,0,0,1,0,0,...,2,4,1,0,0,2,0,0,0,2.0
21,2022-09-28 09:00:00,3.0,9,0,6,1,1,0,0,1,...,2,2,4,0,0,5,0,0,2,3.0
22,2022-09-28 10:00:00,4.0,9,0,6,0,4,0,0,1,...,2,2,2,1,0,0,0,0,1,4.0
23,2022-09-28 11:00:00,5.0,6,1,6,2,0,0,0,1,...,1,7,0,0,0,0,0,0,0,5.0
24,2022-09-28 12:00:00,6.0,13,0,6,2,3,0,0,1,...,4,6,1,0,0,0,0,0,3,6.0
25,2022-09-28 13:00:00,7.0,10,5,6,0,2,0,0,3,...,5,6,3,0,0,0,0,0,1,7.0
26,2022-09-28 14:00:00,8.0,18,0,6,0,1,0,0,0,...,9,3,2,1,0,8,0,0,1,8.0
27,2022-09-28 15:00:00,9.0,8,0,6,1,3,0,0,4,...,5,5,0,1,0,1,0,0,0,0.0
28,2022-09-28 16:00:00,10.0,14,1,6,0,4,0,0,0,...,0,2,0,1,0,5,0,0,3,0.0
29,2022-09-28 17:00:00,11.0,13,0,6,0,2,2,0,0,...,0,5,4,0,0,8,0,0,0,1.0
30,2022-09-28 18:00:00,12.0,15,0,6,1,1,1,0,1,...,2,0,1,0,2,12,0,1,3,2.0
31,2022-09-28 19:00:00,13.0,8,0,6,0,1,0,0,0,...,0,0,2,0,0,4,0,0,3,3.0
32,2022-09-28 20:00:00,14.0,4,0,6,0,3,0,0,0,...,1,0,0,0,0,4,0,0,0,4.0
33,2022-09-28 21:00:00,15.0,7,0,6,0,2,0,0,0,...,0,4,1,0,0,0,1,0,3,5.0
34,2022-09-28 22:00:00,16.0,0,0,6,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6.0
35,2022-09-28 23:00:00,17.0,5,0,5,2,1,1,0,1,...,2,0,0,0,0,1,1,2,2,7.0

In [82]:
#create a df from groupby result
ff = pd.DataFrame(tf)
ff

,Stop_Time,Time_Since_Morning,Station_Name_1-Stop_Reason_1-Remark_1,Station_Name_1-Stop_Reason_3-Remark_8,Station_Name_2-Stop_Reason_2-Remark_2,Station_Name_3-Stop_Reason_3-Remark_3,Station_Name_3-Stop_Reason_4-Remark_4,Station_Name_4-Stop_Reason_3-Remark_10,Station_Name_4-Stop_Reason_3-Remark_13,Station_Name_4-Stop_Reason_3-Remark_5,...,Station_Name_5-Stop_Reason_4-Remark_4,Station_Name_6-Stop_Reason_4-Remark_4,Station_Name_7-Stop_Reason_4-Remark_4,Station_Name_8-Stop_Reason_3-Remark_12,Station_Name_8-Stop_Reason_3-Remark_14,Station_Name_8-Stop_Reason_4-Remark_4,Station_Name_9-Stop_Reason_3-Remark_11,Station_Name_9-Stop_Reason_3-Remark_9,Station_Name_9-Stop_Reason_4-Remark_4,Time_Since_Shift_Start
0,2022-09-27 06:00:00,0.0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
1,2022-09-27 07:00:00,1.0,2,0,6,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1.0
2,2022-09-27 08:00:00,2.0,1,0,6,2,0,0,0,1,...,1,0,0,0,0,0,0,0,0,2.0
3,2022-09-27 09:00:00,3.0,7,2,6,1,3,0,0,2,...,0,1,2,0,0,1,0,0,0,3.0
4,2022-09-27 10:00:00,4.0,5,1,6,0,2,0,0,1,...,0,1,1,0,0,0,0,0,1,4.0
5,2022-09-27 11:00:00,5.0,5,2,6,0,1,0,0,1,...,0,1,0,0,0,1,0,0,1,5.0
6,2022-09-27 12:00:00,6.0,11,0,6,0,4,1,0,1,...,1,0,3,0,0,2,0,1,2,6.0
7,2022-09-27 13:00:00,7.0,13,0,6,1,0,1,0,1,...,1,5,1,0,0,4,1,0,0,7.0
8,2022-09-27 14:00:00,8.0,12,0,6,1,2,0,0,4,...,3,0,1,0,0,0,0,0,0,8.0
9,2022-09-27 15:00:00,9.0,14,1,6,1,5,0,0,1,...,3,1,5,0,0,3,0,0,3,0.0
10,2022-09-27 16:00:00,10.0,13,0,6,0,2,8,0,0,...,0,0,8,0,0,2,0,0,4,0.0
11,2022-09-27 17:00:00,11.0,10,0,6,0,5,3,0,0,...,3,1,0,0,0,4,0,0,1,1.0
12,2022-09-27 18:00:00,12.0,15,1,6,1,4,2,0,1,...,0,3,4,1,0,1,0,0,4,2.0
13,2022-09-27 19:00:00,13.0,9,0,6,0,2,3,0,0,...,0,1,3,0,0,2,0,0,3,3.0
14,2022-09-27 20:00:00,14.0,6,0,6,0,3,1,0,0,...,1,0,1,0,0,1,0,0,2,4.0
15,2022-09-27 21:00:00,15.0,10,0,6,1,2,1,1,1,...,3,2,1,0,0,3,0,1,1,5.0
16,2022-09-27 22:00:00,16.0,11,0,6,1,0,0,0,2,...,6,3,2,0,0,1,0,0,5,6.0
17,2022-09-27 23:00:00,17.0,13,0,4,0,0,0,0,0,...,1,2,5,1,0,6,0,0,1,7.0
18,2022-09-28 06:00:00,0.0,2,0,1,1,0,0,0,0,...,1,1,0,0,0,1,0,0,1,0.0
19,2022-09-28 07:00:00,1.0,7,1,6,1,0,0,0,3,...,3,1,1,0,0,1,0,0,3,1.0
20,2022-09-28 08:00:00,2.0,10,0,6,0,0,1,0,0,...,2,4,1,0,0,2,0,0,0,2.0
21,2022-09-28 09:00:00,3.0,9,0,6,1,1,0,0,1,...,2,2,4,0,0,5,0,0,2,3.0
22,2022-09-28 10:00:00,4.0,9,0,6,0,4,0,0,1,...,2,2,2,1,0,0,0,0,1,4.0
23,2022-09-28 11:00:00,5.0,6,1,6,2,0,0,0,1,...,1,7,0,0,0,0,0,0,0,5.0
24,2022-09-28 12:00:00,6.0,13,0,6,2,3,0,0,1,...,4,6,1,0,0,0,0,0,3,6.0
25,2022-09-28 13:00:00,7.0,10,5,6,0,2,0,0,3,...,5,6,3,0,0,0,0,0,1,7.0
26,2022-09-28 14:00:00,8.0,18,0,6,0,1,0,0,0,...,9,3,2,1,0,8,0,0,1,8.0
27,2022-09-28 15:00:00,9.0,8,0,6,1,3,0,0,4,...,5,5,0,1,0,1,0,0,0,0.0
28,2022-09-28 16:00:00,10.0,14,1,6,0,4,0,0,0,...,0,2,0,1,0,5,0,0,3,0.0
29,2022-09-28 17:00:00,11.0,13,0,6,0,2,2,0,0,...,0,5,4,0,0,8,0,0,0,1.0
30,2022-09-28 18:00:00,12.0,15,0,6,1,1,1,0,1,...,2,0,1,0,2,12,0,1,3,2.0
31,2022-09-28 19:00:00,13.0,8,0,6,0,1,0,0,0,...,0,0,2,0,0,4,0,0,3,3.0
32,2022-09-28 20:00:00,14.0,4,0,6,0,3,0,0,0,...,1,0,0,0,0,4,0,0,0,4.0
33,2022-09-28 21:00:00,15.0,7,0,6,0,2,0,0,0,...,0,4,1,0,0,0,1,0,3,5.0
34,2022-09-28 22:00:00,16.0,0,0,6,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6.0
35,2022-09-28 23:00:00,17.0,5,0,5,2,1,1,0,1,...,2,0,0,0,0,1,1,2,2,7.0

In [83]:
ff.to_csv(r'C:\Users\priya\Projects\new_working\trial_data_27_28.csv', index=False)

In [73]:
#split data into train and test by 2022-10-08 00:00:00
# train = ff[ff['Stop_Time'] < '2022-10-08 00:00:00']
# test = ff[ff['Stop_Time'] >= '2022-10-08 00:00:00']
# train.to_csv(r'C:\Users\priya\Projects\new_working\train_time_data.csv', index=False)
# test.to_csv(r'C:\Users\priya\Projects\new_working\test_time_data.csv', index=False)

In [74]:
l1

['Station_Name_1-Stop_Reason_1-Remark_1',
 'Station_Name_1-Stop_Reason_3-Remark_12',
 'Station_Name_1-Stop_Reason_3-Remark_5',
 'Station_Name_2-Stop_Reason_2-Remark_2',
 'Station_Name_3-Stop_Reason_3-Remark_11',
 'Station_Name_3-Stop_Reason_3-Remark_3',
 'Station_Name_3-Stop_Reason_3-Remark_8',
 'Station_Name_3-Stop_Reason_3-Remark_9',
 'Station_Name_3-Stop_Reason_4-Remark_4',
 'Station_Name_4-Stop_Reason_3-Remark_10',
 'Station_Name_4-Stop_Reason_4-Remark_4',
 'Station_Name_5-Stop_Reason_3-Remark_6',
 'Station_Name_5-Stop_Reason_4-Remark_4',
 'Station_Name_6-Stop_Reason_4-Remark_4',
 'Station_Name_7-Stop_Reason_4-Remark_4',
 'Station_Name_8-Stop_Reason_3-Remark_14',
 'Station_Name_8-Stop_Reason_4-Remark_4',
 'Station_Name_9-Stop_Reason_3-Remark_13',
 'Station_Name_9-Stop_Reason_3-Remark_7',
 'Station_Name_9-Stop_Reason_4-Remark_4']